// Référence statique pays → villes, pour les listes déroulantes éditables
// (datalist) des champs Pays/Ville du formulaire hôtels. La capitale est
// toujours incluse ; des villes touristiques s'y ajoutent pour les
// destinations les plus courantes de l'agence. Un pays ou une ville absent
// de cette liste reste saisissable librement (datalist, pas un select
// fermé) — pas besoin de mettre à jour ce fichier pour ajouter un hôtel
// dans une ville non répertoriée.
//
// ⚠️ Arabie Saoudite : villes saintes nommées "Makka" et "Madina" (et non
// "La Mecque"/"Médine") — demande explicite, à ne pas "franciser".

export const CITIES_BY_COUNTRY = {
  // --- Destinations enrichies (capitale + villes touristiques) ---
  "Arabie Saoudite": ["Riyad", "Jeddah", "Makka", "Madina", "Dammam", "Taëf", "Abha", "Yanbu"],
  "Maroc": ["Rabat", "Casablanca", "Marrakech", "Fès", "Tanger", "Agadir", "Chefchaouen", "Essaouira", "Merzouga", "Oujda"],
  "Turquie": ["Ankara", "Istanbul", "Antalya", "Izmir", "Bodrum", "Cappadoce (Nevşehir)", "Bursa", "Fethiye"],
  "France": ["Paris", "Marseille", "Lyon", "Nice", "Bordeaux", "Strasbourg", "Toulouse", "Cannes"],
  "Espagne": ["Madrid", "Barcelone", "Séville", "Valence", "Malaga", "Grenade", "Palma de Majorque"],
  "Italie": ["Rome", "Milan", "Venise", "Florence", "Naples", "Turin", "Vérone"],
  "Émirats arabes unis": ["Abou Dabi", "Dubaï", "Charjah", "Ras el Khaïmah", "Fujaïrah"],
  "Égypte": ["Le Caire", "Alexandrie", "Charm el-Cheikh", "Hurghada", "Louxor", "Assouan"],
  "Tunisie": ["Tunis", "Sousse", "Hammamet", "Djerba", "Sfax", "Tozeur"],
  "Qatar": ["Doha", "Al Wakrah", "Al Rayyan"],
  "Koweït": ["Koweït"],
  "Bahreïn": ["Manama"],
  "Oman": ["Mascate", "Salalah", "Sohar"],
  "Jordanie": ["Amman", "Petra (Wadi Musa)", "Aqaba", "Mer Morte"],
  "Malaisie": ["Kuala Lumpur", "Langkawi", "Penang", "Malacca"],
  "Indonésie": ["Jakarta", "Bali (Denpasar)", "Yogyakarta", "Bandung"],
  "Thaïlande": ["Bangkok", "Phuket", "Chiang Mai", "Pattaya", "Krabi"],
  "Royaume-Uni": ["Londres", "Manchester", "Édimbourg", "Liverpool", "Birmingham"],
  "Allemagne": ["Berlin", "Munich", "Francfort", "Hambourg", "Cologne"],
  "Grèce": ["Athènes", "Santorin", "Mykonos", "Rhodes", "Thessalonique"],
  "Portugal": ["Lisbonne", "Porto", "Faro (Algarve)", "Madère (Funchal)"],
  "États-Unis": ["Washington", "New York", "Los Angeles", "Miami", "Las Vegas", "San Francisco", "Orlando"],
  "Canada": ["Ottawa", "Toronto", "Montréal", "Vancouver", "Québec"],
  "Suisse": ["Berne", "Genève", "Zurich", "Lausanne", "Lucerne"],
  "Autriche": ["Vienne", "Salzbourg", "Innsbruck"],
  "Pays-Bas": ["Amsterdam", "Rotterdam", "La Haye", "Utrecht"],
  "Sénégal": ["Dakar", "Saly", "Saint-Louis"],
  "Algérie": ["Alger", "Oran", "Constantine", "Annaba"],
  "Mauritanie": ["Nouakchott", "Nouadhibou"],
  "Liban": ["Beyrouth", "Byblos", "Baalbek"],
  "Maldives": ["Malé"],
  "Chine": ["Pékin", "Shanghai", "Hong Kong", "Guangzhou", "Xi'an"],
  "Japon": ["Tokyo", "Kyoto", "Osaka", "Hokkaido"],
  "Corée du Sud": ["Séoul", "Busan", "Jeju"],
  "Inde": ["New Delhi", "Bombay", "Agra", "Jaipur", "Goa"],
  "Australie": ["Canberra", "Sydney", "Melbourne", "Brisbane", "Gold Coast"],
  "Brésil": ["Brasilia", "Rio de Janeiro", "São Paulo", "Salvador de Bahia"],
  "Mexique": ["Mexico", "Cancún", "Guadalajara", "Playa del Carmen"],

  // --- Autres pays du monde : capitale uniquement (liste toujours saisissable librement) ---
  "Afghanistan": ["Kaboul"],
  "Afrique du Sud": ["Pretoria", "Le Cap", "Johannesburg"],
  "Albanie": ["Tirana"],
  "Andorre": ["Andorre-la-Vieille"],
  "Angola": ["Luanda"],
  "Antigua-et-Barbuda": ["Saint John's"],
  "Argentine": ["Buenos Aires"],
  "Arménie": ["Erevan"],
  "Azerbaïdjan": ["Bakou"],
  "Bahamas": ["Nassau"],
  "Bangladesh": ["Dacca"],
  "Barbade": ["Bridgetown"],
  "Belgique": ["Bruxelles", "Anvers", "Bruges"],
  "Belize": ["Belmopan"],
  "Bénin": ["Porto-Novo", "Cotonou"],
  "Bhoutan": ["Thimphou"],
  "Biélorussie": ["Minsk"],
  "Birmanie (Myanmar)": ["Naypyidaw", "Rangoun"],
  "Bolivie": ["Sucre", "La Paz"],
  "Bosnie-Herzégovine": ["Sarajevo"],
  "Botswana": ["Gaborone"],
  "Brunei": ["Bandar Seri Begawan"],
  "Bulgarie": ["Sofia"],
  "Burkina Faso": ["Ouagadougou"],
  "Burundi": ["Gitega"],
  "Cambodge": ["Phnom Penh", "Siem Reap"],
  "Cameroun": ["Yaoundé", "Douala"],
  "Cap-Vert": ["Praia"],
  "République centrafricaine": ["Bangui"],
  "Chili": ["Santiago"],
  "Chypre": ["Nicosie"],
  "Colombie": ["Bogota", "Carthagène"],
  "Comores": ["Moroni"],
  "Congo (République du)": ["Brazzaville"],
  "Congo (République démocratique du)": ["Kinshasa"],
  "Corée du Nord": ["Pyongyang"],
  "Costa Rica": ["San José"],
  "Côte d'Ivoire": ["Yamoussoukro", "Abidjan"],
  "Croatie": ["Zagreb", "Dubrovnik", "Split"],
  "Cuba": ["La Havane", "Varadero"],
  "Danemark": ["Copenhague"],
  "Djibouti": ["Djibouti"],
  "Dominique": ["Roseau"],
  "République dominicaine": ["Saint-Domingue", "Punta Cana"],
  "Équateur": ["Quito", "Guayaquil"],
  "Érythrée": ["Asmara"],
  "Eswatini": ["Mbabane"],
  "Estonie": ["Tallinn"],
  "Éthiopie": ["Addis-Abeba"],
  "Fidji": ["Suva"],
  "Finlande": ["Helsinki"],
  "Gabon": ["Libreville"],
  "Gambie": ["Banjul"],
  "Géorgie": ["Tbilissi"],
  "Ghana": ["Accra"],
  "Grenade": ["Saint-Georges"],
  "Guatemala": ["Guatemala"],
  "Guinée": ["Conakry"],
  "Guinée-Bissau": ["Bissau"],
  "Guinée équatoriale": ["Malabo"],
  "Guyana": ["Georgetown"],
  "Haïti": ["Port-au-Prince"],
  "Honduras": ["Tegucigalpa"],
  "Hongrie": ["Budapest"],
  "Îles Marshall": ["Majuro"],
  "Îles Salomon": ["Honiara"],
  "Irak": ["Bagdad"],
  "Iran": ["Téhéran"],
  "Irlande": ["Dublin"],
  "Islande": ["Reykjavik"],
  "Israël": ["Jérusalem", "Tel Aviv"],
  "Jamaïque": ["Kingston", "Montego Bay"],
  "Kazakhstan": ["Astana", "Almaty"],
  "Kenya": ["Nairobi", "Mombasa"],
  "Kirghizistan": ["Bichkek"],
  "Kiribati": ["Tarawa"],
  "Kosovo": ["Pristina"],
  "Laos": ["Vientiane"],
  "Lesotho": ["Maseru"],
  "Lettonie": ["Riga"],
  "Liberia": ["Monrovia"],
  "Libye": ["Tripoli"],
  "Liechtenstein": ["Vaduz"],
  "Lituanie": ["Vilnius"],
  "Luxembourg": ["Luxembourg"],
  "Macédoine du Nord": ["Skopje"],
  "Madagascar": ["Antananarivo"],
  "Malawi": ["Lilongwe"],
  "Mali": ["Bamako"],
  "Malte": ["La Valette"],
  "Maurice": ["Port-Louis"],
  "Micronésie": ["Palikir"],
  "Moldavie": ["Chisinau"],
  "Monaco": ["Monaco"],
  "Mongolie": ["Oulan-Bator"],
  "Monténégro": ["Podgorica"],
  "Mozambique": ["Maputo"],
  "Namibie": ["Windhoek"],
  "Nauru": ["Yaren"],
  "Népal": ["Katmandou"],
  "Nicaragua": ["Managua"],
  "Niger": ["Niamey"],
  "Nigeria": ["Abuja", "Lagos"],
  "Norvège": ["Oslo"],
  "Nouvelle-Zélande": ["Wellington", "Auckland"],
  "Ouganda": ["Kampala"],
  "Ouzbékistan": ["Tachkent", "Samarcande"],
  "Pakistan": ["Islamabad", "Karachi"],
  "Palaos": ["Ngerulmud"],
  "Palestine": ["Ramallah", "Jérusalem-Est"],
  "Panama": ["Panama"],
  "Papouasie-Nouvelle-Guinée": ["Port Moresby"],
  "Paraguay": ["Asuncion"],
  "Pérou": ["Lima", "Cusco"],
  "Philippines": ["Manille", "Cebu"],
  "Pologne": ["Varsovie", "Cracovie"],
  "Roumanie": ["Bucarest"],
  "Russie": ["Moscou", "Saint-Pétersbourg"],
  "Rwanda": ["Kigali"],
  "Saint-Christophe-et-Niévès": ["Basseterre"],
  "Sainte-Lucie": ["Castries"],
  "Saint-Marin": ["Saint-Marin"],
  "Saint-Vincent-et-les-Grenadines": ["Kingstown"],
  "Salvador": ["San Salvador"],
  "Samoa": ["Apia"],
  "Sao Tomé-et-Principe": ["Sao Tomé"],
  "Serbie": ["Belgrade"],
  "Seychelles": ["Victoria"],
  "Sierra Leone": ["Freetown"],
  "Singapour": ["Singapour"],
  "Slovaquie": ["Bratislava"],
  "Slovénie": ["Ljubljana"],
  "Somalie": ["Mogadiscio"],
  "Soudan": ["Khartoum"],
  "Soudan du Sud": ["Djouba"],
  "Sri Lanka": ["Colombo"],
  "Suède": ["Stockholm"],
  "Suriname": ["Paramaribo"],
  "Syrie": ["Damas"],
  "Tadjikistan": ["Douchanbé"],
  "Taïwan": ["Taipei"],
  "Tanzanie": ["Dodoma", "Zanzibar"],
  "Tchad": ["N'Djamena"],
  "Timor oriental": ["Dili"],
  "Togo": ["Lomé"],
  "Tonga": ["Nuku'alofa"],
  "Trinité-et-Tobago": ["Port-d'Espagne"],
  "Turkménistan": ["Achgabat"],
  "Tuvalu": ["Funafuti"],
  "Ukraine": ["Kiev"],
  "Uruguay": ["Montevideo"],
  "Vanuatu": ["Port-Vila"],
  "Vatican": ["Vatican"],
  "Venezuela": ["Caracas"],
  "Vietnam": ["Hanoï", "Hô-Chi-Minh-Ville"],
  "Yémen": ["Sanaa"],
  "Zambie": ["Lusaka"],
  "Zimbabwe": ["Harare"],
};

export const COUNTRIES = Object.keys(CITIES_BY_COUNTRY).sort((a, b) => a.localeCompare(b, "fr"));

export function getCitiesForCountry(country) {
  return CITIES_BY_COUNTRY[country] || [];
}
