// Icône Material Symbols Rounded (police chargée par app/admin/layout.js,
// liste des glyphes : ADMIN_ICON_NAMES). translate="no" : le nom de ligature
// ("group", "hotel"...) ne doit jamais passer par le traducteur DOM.
// ⚠️ Toute nouvelle icône doit être ajoutée à ADMIN_ICON_NAMES (sinon elle
// s'affiche comme du texte brut) — voir designadmin.md.
export default function Icon({ name, size = 20, fill = false, className = "", style }) {
  return (
    <span
      aria-hidden="true"
      translate="no"
      data-fill={fill ? "1" : undefined}
      className={`gf-icon ${className}`}
      style={{ fontSize: size, ...style }}
    >
      {name}
    </span>
  );
}

// Glyphes inclus dans la police téléchargée (sous-ensemble Google Fonts,
// paramètre icon_names — doit rester trié alphabétiquement).
export const ADMIN_ICON_NAMES = [
  "account_balance_wallet",
  "add",
  "add_circle",
  "admin_panel_settings",
  "airplane_ticket",
  "arrow_back",
  "arrow_forward",
  "assignment",
  "badge",
  "bar_chart",
  "bed",
  "block",
  "bolt",
  "calendar_month",
  "campaign",
  "chat",
  "check_circle",
  "chevron_left",
  "chevron_right",
  "close",
  "confirmation_number",
  "contacts",
  "content_copy",
  "credit_card",
  "delete",
  "description",
  "domain_add",
  "download",
  "edit",
  "event",
  "event_seat",
  "expand_more",
  "fact_check",
  "flight",
  "flight_takeoff",
  "forum",
  "group",
  "groups",
  "help",
  "history",
  "hotel",
  "hotel_class",
  "hourglass_top",
  "how_to_reg",
  "inbox",
  "info",
  "insights",
  "inventory_2",
  "key",
  "left_panel_close",
  "left_panel_open",
  "link",
  "list_alt",
  "lock",
  "logout",
  "luggage",
  "manage_accounts",
  "menu",
  "menu_book",
  "mic",
  "monitor_heart",
  "mosque",
  "newspaper",
  "notifications",
  "notifications_active",
  "open_in_new",
  "payments",
  "person",
  "person_add",
  "play_arrow",
  "qr_code_2",
  "receipt_long",
  "redeem",
  "room_service",
  "savings",
  "schedule",
  "science",
  "search",
  "send",
  "settings",
  "shield",
  "smart_toy",
  "space_dashboard",
  "stop_circle",
  "storefront",
  "support_agent",
  "task_alt",
  "thumb_down",
  "thumb_up",
  "travel_explore",
  "upload",
  "verified",
  "view_carousel",
  "visibility",
  "visibility_off",
  "warning",
];
